apiVersion: v1
kind: Service
metadata:
  name: k8s-pod-id-headless
spec:
  clusterIP: None
  selector:
    app: k8s-pod-id
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-pod-id
spec:
  serviceName: k8s-pod-id-headless
  replicas: 3
  selector:
    matchLabels:
      app: k8s-pod-id
  template:
    metadata:
      labels:
        app: k8s-pod-id
    spec:
      containers:
        - name: worker
          image: k8s_pod_id:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: worker-env
          env:
            - name: SHARD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-pod-id-svc
spec:
  type: LoadBalancer
  selector:
    app: k8s-pod-id
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
